### ISSUE TITLE
Error on using adding to cart including coupon, coupon code cannot be applied to cart content

### ISSUE THREAD

**Issue by excitingw** [cedaro/woocommerce-coupon-links#6]
Hi,

When we use the url to add the product to cart and apply coupon code at the same time we receive an error that the coupon cannot be applied to the cart content. When we reload the url, it works like a charm.. Any ideas why it's not working?

https://www.excitingwine.nl/winkelwagen/?add_to_cart=695&coupon_code=jointhelama

Best wishes

**Comment by kcargile** [comment]
We were having the same issue with a coupon that is restricted to a certain product. 

In that case, it appears that ```woocommerce_cart_loaded_from_session hook``` is fired too early in the cart "lifecycle". That is, the coupon is applied before the product is added to the cart, which is not possible since such a coupon cannot be applied to an empty cart.

I was able to work around the issue by modifying woocommerce-coupon-links.php to hook an action later in the lifecycle. 

Try replacing:

```add_action( 'woocommerce_cart_loaded_from_session', 'cedaro_woocommerce_coupon_links' );```

with

```add_action( 'woocommerce_before_calculate_totals', 'cedaro_woocommerce_coupon_links' );```

and see if you have different results.

**Comment by bradyvercher** [comment]
This sounds like it should be fixed with the change in #7. Let us know if y'all run into any issues after testing, though.

**Comment by bradyvercher** [comment]
Apparently this is a bit more complex than I originally thought. I've pushed an update in cbbb73f that should take care of it, so if everyone can confirm that fixes the issue for them, I'll tag the next release.

**Comment by lkraav** [comment]
I'm still seeing this error and the coupon does not get applied. I looked at the commit and it talks about redirect away from add-to-cart. That's exactly what I'm doing, because I send people directly to checkout - single product selection doesn't require a cart screen at all.

Thoughts on how to debug?

**Comment by bradyvercher** [comment]
Hi @lkraav, how are you redirecting directly to checkout? You might need to make sure that happens late enough that the add to cart or `wp_loaded` actions fire.

I've been looking into adding a unit testing suite, so let me know if you find anything out and I'll see if it's something we can automate.

**Comment by lkraav** [comment]
I'm simply assigning both Cart and Checkout pages to be the same "Secure Checkout" page in WC Settings panel
